name: Node-Practice-NASA CI
on:
  push:
    branches: [ main ] # When push to these branches then trigger
  pull_request:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # pre-made actions from github actions that share
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        with: 
          node-version: '20'  # give specific version
      - run: npm install
      - run: npm run build --prefix client
  #deploy:
   # needs: build # Default github action will run these jobs in parallel, so put needs property will tell it start after build finish and succeed